yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('create/', views.post_create, name='post_create'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from yatube.settings import LEN_OBJ_NAME

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название сообщества'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Слаг (человеко-читаемый URL для страницы)'
    )
    description = models.TextField(verbose_name='Описание сообщества')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Сообщество',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:LEN_OBJ_NAME]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Связанный пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Напишите комментарий'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария'
    )

    def __str__(self):
        return (
            f'Комментарий к посту с id {self.post.id}:'
            f'{self.text[:LEN_OBJ_NAME]}'
        )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Коммент'
        verbose_name_plural = 'Комменты'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    def __str__(self):
        return (
            f'Пользователь {self.user} подписан '
            f'на автора {self.author}'
        )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_subscription'
            )
        ]

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
            'image': 'Добавить картинку'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {'text': 'Текст комментария'}

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from core.utils import add_paginator
from .models import Post, Group, Comment, Follow, User
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from yatube.settings import NUMBER_OF_POSTS


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('group', 'author').all()
    page_obj = add_paginator(request, post_list, NUMBER_OF_POSTS)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = add_paginator(request, post_list, NUMBER_OF_POSTS)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.select_related('author').filter(author=author)
    page_obj = add_paginator(request, post_list, NUMBER_OF_POSTS)
    following = request.user.is_authenticated and Follow.objects.filter(
        author=author,
        user=request.user
    ).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = Post.objects.select_related('author').get(pk=post_id)
    comments = Comment.objects.prefetch_related('post').filter(post=post)
    form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect("posts:profile", request.user)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect("posts:post_detail", post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = add_paginator(request, post_list, NUMBER_OF_POSTS)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        follow, created = Follow.objects.get_or_create(
            user=request.user,
            author=author,
        )
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=author.username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {% if is_edit %}       
    Редактировать запись
  {% else %}
    Добавить запись  
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}       
              Редактировать запись
            {% else %}
              Добавить запись  
            {% endif %}
          </div>
          <div class="card-body"> 
            <form method="post" enctype="multipart/form-data"
              {% if is_edit %}
                action="{% url 'posts:post_edit' form.instance.pk %}"
              {% else %}
                action="{% url 'posts:post_create' %}"
              {% endif %}
            >
              {% csrf_token %}

              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  {% if field.errors %}
                    <ol>
                    {% for error in field.errors %}
                        <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                    </ol>
                  {% endif %}
                  
                  <label for="id_{{ field.name }}">
                    {{ field.label_tag }} 
                    {% if field.field.required %}                
                      <span class="required text-danger" >*</span> 
                    {% endif %}                 
                  </label>
                  {% if field.name == 'image' %}
                    {% if is_edit %}
                      На данный момент: 
                      {% if form.instance.image %}
                        <a href="/media/{{form.instance.image}}">/media/{{form.instance.image}}</a> 
                        <input type="checkbox" name="image-clear" id="image-clear_id">
                        <label for="image-clear_id">Очистить</label><br>
                      {% else %}
                        Пост без картинки
                      <br><br>
                      {% endif %}
                      Изменить
                    {% endif%}
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">
                  {% else %}
                  {{ field }}
                  {% endif %}
                  
                  
                  {% if field.help_text %}
                    <small id="id_text-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
    
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}       
                    Сохранить
                  {% else %}
                    Добавить  
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{% load thumbnail %}
{% block title %}
  Подписки на авторов
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  <div class="container py-5">
  {% cache 20 index_page with page_obj %}
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaks }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">
          подробная информация
        </a>
      </article> 
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{post.group.title}}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endcache %} 
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}
 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <body>
    <main>
      {% block content %}
      <div class="container">
        <h1>{{ group.title }}</h1>
        <h5>
           {{ group.description|linebreaks }}
        </h5>
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
                </a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>  
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}    
            <p>
              {{ post.text|linebreaks }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">
              подробная информация
            </a>         
          </article>
          {% if post.group %}   
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{post.group.title}}</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}

        {% include 'posts/includes/paginator.html' %}
      </div>  

      {% endblock %}
    </main>
    <footer class="page-footer font-small blue border-top">
      <div class="footer-copyright text-center py-3">© 2020 Copyright 
        <p><span style="color:red">Ya</span>tube</p> 
      </div>    
    </footer>
  </body>
</html>
  

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
  {% cache 20 index_page with page_obj %}
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaks }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">
          подробная информация
        </a>
      </article> 
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{post.group.title}}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endcache %} 
  {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}
 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Пост {{post|truncatechars:30}}{% endblock %}
{% block content %}
    <div class="container py-5">
        <div class="row">
        <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    Дата публикации: {{ post.pub_date }}
                </li>
                {% if post.group %} 
                    <li class="list-group-item">
                        Группа: {{ post.group }} <br>
                        <a href="{% url 'posts:group_list' post.group.slug %}">
                        все записи группы
                        </a>
                    </li>
                {% endif %}
                <li class="list-group-item">
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Всего постов автора:  <span >{{ post_author.posts.count }}</span>
                </li>
                <li class="list-group-item">
                    <a href="{% url 'posts:profile' post.author %}">
                    все посты пользователя
                    </a>
                </li>
            </ul>
        </aside>
        <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
            {{ this_post.text|linebreaks }}
            </p>
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
                редактировать запись
            </a>
            {% include 'includes/comment.html' %}
        </article>
        </div>
    </div> 

{% endblock %} 

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} {{author.get_full_name }} Профайл пользователя {% endblock %}
{% block content %}
    <div class="container py-5"> 
      <div class="mb-5">       
        <h1>Все посты пользователя {{author.get_full_name}} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3>
        {% if request.user != author %}   
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
              >
                Подписаться
              </a>
          {% endif %}
        {% endif %}
      </div>
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                  Автор: {{author}}
                  <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
                </li>
                <li>
                  Дата публикации: {{ post.pub_date }}
                </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
              {{ post.text|linebreaks }}
            </p>
            <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        </article>  

        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>  
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}      

    {% include 'posts/includes/paginator.html' %}
    </div>

{% endblock %} 